---
- apt:
    name: zabbix-agent
    state: present

- lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server="
    line: "Server={{ zabbix_server_ip }}"

- lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive="
    line: "ServerActive={{ zabbix_server_ip }}"
